Acquire::http::Proxy "http://host.docker.internal:18080";
Acquire::https::Proxy "http://host.docker.internal:18080";

Acquire::http::Proxy::mirrors.tools.huawei.com "DIRECT";
Acquire::https::Proxy::mirrors.tools.huawei.com "DIRECT";

Acquire::https::Verify-Peer "false";
Acquire::https::Verify-Host "false";